# Generated by Django 5.1.1 on 2024-10-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_searchlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='keywords',
            new_name='tags',
        ),
    ]
