# Generated by Django 5.1.1 on 2024-10-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_keywords_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='visible',
            new_name='public',
        ),
    ]
